name = "cinenovatv"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

routes = [
  { pattern = "cinenovatv.com/*", zone_name = "cinenovatv.com" },
  { pattern = "www.cinenovatv.com/*", zone_name = "cinenovatv.com" },
]

[vars]
NODE_ENV = "production"
TMDB_API_KEY = "be15cf50e79cec926bbbddb3ab5dd819"
OMDB_API_KEY = "9a684507"
